"""Align payments table with code

Revision ID: b26bdb9beb3a
Revises: e862c2940ff5
Create Date: 2025-06-29 17:26:59.451644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26bdb9beb3a'
down_revision: Union[str, Sequence[str], None] = 'e862c2940ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('payments', sa.Column('invoice_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'payments', ['invoice_id'])
    op.drop_column('payments', 'payment_system')
    op.drop_column('payments', 'cryptocloud_invoice_id')
    op.drop_column('payments', 'telegram_payment_charge_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('telegram_payment_charge_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('cryptocloud_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_system', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'invoice_id')
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
